apiVersion: v1
kind: Secret
metadata:
  name: supermarket-secrets
  namespace: supermarket
type: Opaque
stringData:
  postgres-password: postgres
  jwt-secret: supermarket-jwt-secret-key-must-be-at-least-32-characters
  aws-access-key: YOUR_ACCESS_KEY
  aws-secret-key: YOUR_SECRET_KEY
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: supermarket-config
  namespace: supermarket
data:
  kafka-servers: kafka:9092
  elasticsearch-url: http://elasticsearch:9200
  product-service-url: http://product-service:8080
